// Merge operations — wave PR pipeline replacing wave-worktree.sh merge + pr-ops.sh.
// Why: centralize merge lifecycle in daemon, remove bash script drift (Plan 698).

use crate::server::state_init::ConnPool;
use crate::workspace::events::{EventLogger, WorkspaceAction};
use crate::workspace::git_connector::{GitConnector, MergeMethod, PrReadiness};
use crate::workspace::wave_ops::pool_err;
use rusqlite::params;
use serde::{Deserialize, Serialize};
use std::path::Path;
use std::thread;
use std::time::Duration;

/// Outcome of a completed merge pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergeResult {
    pub pr_number: i64,
    pub pr_url: String,
    pub merged: bool,
}

/// Poll interval and max attempts for PR readiness.
const POLL_INTERVAL_SECS: u64 = 10;
const MAX_POLL_ATTEMPTS: u32 = 30;

/// Full merge pipeline for a wave worktree.
///
/// Steps: commit → rebase → push → create PR → poll readiness → merge → DB update.
/// Events are recorded at each stage for audit trail.
pub fn merge_wave(
    wave_db_id: i64,
    repo_slug: &str,
    connector: &dyn GitConnector,
    event_logger: &EventLogger,
    pool: &ConnPool,
) -> Result<MergeResult, String> {
    // a. Get workspace info from workspaces table
    let (path_str, branch, workspace_id) = {
        let conn = pool.get().map_err(pool_err)?;
        conn.query_row(
            "SELECT ws.path, ws.branch, ws.workspace_id \
             FROM workspaces ws \
             WHERE ws.wave_db_id = ?1 AND ws.status = 'active'",
            params![wave_db_id],
            |row| {
                let path: String = row.get(0)?;
                let branch: String = row.get(1)?;
                let ws_id: String = row.get(2)?;
                Ok((path, branch, ws_id))
            },
        )
        .map_err(|e| format!("no active workspace for wave {wave_db_id}: {e}"))?
    };
    let path = Path::new(&path_str);

    // Derive commit message from wave plan context
    let plan_id: i64 = {
        let conn = pool.get().map_err(pool_err)?;
        conn.query_row(
            "SELECT plan_id FROM waves WHERE id = ?1",
            params![wave_db_id],
            |row| row.get(0),
        )
        .map_err(|e| format!("wave {wave_db_id} not found: {e}"))?
    };
    let commit_msg = format!("feat(plan-{plan_id}): wave {wave_db_id}");

    // b. Commit staged changes
    let sha = connector.commit(path, &commit_msg)?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::GitCommit,
            None,
            Some(&sha),
            None,
        )
        .map_err(|e| format!("event record failed: {e}"))?;

    // c. Rebase onto origin/main
    connector.rebase(path, "origin/main")?;

    // d. Push with force-with-lease (safe after rebase)
    connector.push(path, &branch, true)?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::GitPush,
            None,
            Some(&format!("pushed {branch}")),
            None,
        )
        .map_err(|e| format!("event record failed: {e}"))?;

    // e. Create PR
    let pr_title = format!("feat(plan-{plan_id}): wave {wave_db_id}");
    let pr_body = format!(
        "Automated merge for plan {plan_id} wave {wave_db_id}.\n\nGenerated by convergio-daemon."
    );
    let pr_info = connector.create_pr(repo_slug, &branch, "main", &pr_title, &pr_body)?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::PrCreated,
            None,
            Some(&format!("PR #{}", pr_info.number)),
            Some(&pr_info.url),
        )
        .map_err(|e| format!("event record failed: {e}"))?;

    // f. Poll PR readiness (every 10s, max 30 attempts)
    let mut attempts = 0u32;
    let ready = loop {
        let status = pr_readiness_check(connector, repo_slug, pr_info.number)?;
        if status.mergeable && status.ci_passed && status.unresolved_threads == 0 {
            break true;
        }
        attempts += 1;
        if attempts >= MAX_POLL_ATTEMPTS {
            break false;
        }
        thread::sleep(Duration::from_secs(POLL_INTERVAL_SECS));
    };

    if !ready {
        return Err(format!(
            "PR #{} not ready after {} attempts",
            pr_info.number, MAX_POLL_ATTEMPTS
        ));
    }

    // g. Merge PR via squash
    connector.merge_pr(repo_slug, pr_info.number, MergeMethod::Squash)?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::PrMerged,
            None,
            Some(&format!("PR #{} squash-merged", pr_info.number)),
            None,
        )
        .map_err(|e| format!("event record failed: {e}"))?;

    // i. Update waves table: status='done', pr_number, pr_url
    pool.get()
        .map_err(pool_err)?
        .execute(
            "UPDATE waves SET status='done', pr_number=?1, pr_url=?2 WHERE id=?3",
            params![pr_info.number, pr_info.url, wave_db_id],
        )
        .map_err(|e| format!("update waves failed: {e}"))?;

    Ok(MergeResult {
        pr_number: pr_info.number,
        pr_url: pr_info.url,
        merged: true,
    })
}

/// Thin wrapper around connector.pr_readiness for external callers.
pub fn pr_readiness_check(
    connector: &dyn GitConnector,
    repo: &str,
    pr_number: i64,
) -> Result<PrReadiness, String> {
    connector.pr_readiness(repo, pr_number)
}

#[cfg(test)]
#[path = "merge_ops_tests.rs"]
mod tests;
