// Merge operations — wave PR pipeline replacing wave-worktree.sh merge + pr-ops.sh.
// Why: centralize merge lifecycle in daemon, remove bash script drift (Plan 698).

use crate::server::state_init::ConnPool;
use crate::workspace::core::WorkspaceError;
use crate::workspace::events::{EventLogger, WorkspaceAction};
use crate::workspace::git_connector::{GitConnector, GitError, MergeMethod, PrReadiness};
use rusqlite::params;
use serde::{Deserialize, Serialize};
use std::path::Path;
use tokio::time::{sleep, Duration};

type Result<T> = std::result::Result<T, WorkspaceError>;

/// Outcome of a completed merge pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergeResult {
    pub pr_number: i64,
    pub pr_url: String,
    pub merged: bool,
}

const POLL_INTERVAL_SECS: u64 = 10;
const MAX_POLL_ATTEMPTS: u32 = 30;

/// Full merge pipeline for a wave worktree.
///
/// Steps: commit -> rebase -> push -> create PR -> poll readiness -> merge -> DB update.
pub async fn merge_wave(
    wave_db_id: i64,
    repo_slug: &str,
    connector: &dyn GitConnector,
    event_logger: &EventLogger,
    pool: &ConnPool,
) -> Result<MergeResult> {
    let (path_str, branch, workspace_id) = {
        let conn = pool.get()?;
        conn.query_row(
            "SELECT ws.path, ws.branch, ws.workspace_id \
             FROM workspaces ws \
             WHERE ws.wave_db_id = ?1 AND ws.status = 'active'",
            params![wave_db_id],
            |row| {
                let path: String = row.get(0)?;
                let branch: String = row.get(1)?;
                let ws_id: String = row.get(2)?;
                Ok((path, branch, ws_id))
            },
        )
        .map_err(|e| WorkspaceError::NotFound(format!("wave {wave_db_id}: {e}")))?
    };
    let path = Path::new(&path_str);

    let plan_id: i64 = {
        let conn = pool.get()?;
        conn.query_row(
            "SELECT plan_id FROM waves WHERE id = ?1",
            params![wave_db_id],
            |row| row.get(0),
        )
        .map_err(|e| WorkspaceError::NotFound(format!("wave {wave_db_id}: {e}")))?
    };
    let commit_msg = format!("feat(plan-{plan_id}): wave {wave_db_id}");

    let sha = connector
        .commit(path, &commit_msg)
        .map_err(|e| WorkspaceError::Git(e.to_string()))?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::GitCommit,
            None,
            Some(&sha),
            None,
        )
        .map_err(|e| WorkspaceError::Event(e.to_string()))?;

    connector
        .rebase(path, "origin/main")
        .map_err(|e| WorkspaceError::Git(e.to_string()))?;

    connector
        .push(path, &branch, true)
        .map_err(|e| WorkspaceError::Git(e.to_string()))?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::GitPush,
            None,
            Some(&format!("pushed {branch}")),
            None,
        )
        .map_err(|e| WorkspaceError::Event(e.to_string()))?;

    let pr_title = format!("feat(plan-{plan_id}): wave {wave_db_id}");
    let pr_body = format!(
        "Automated merge for plan {plan_id} wave {wave_db_id}.\n\nGenerated by convergio-daemon."
    );
    let pr_info = connector
        .create_pr(repo_slug, &branch, "main", &pr_title, &pr_body)
        .await
        .map_err(|e| WorkspaceError::Merge(e.to_string()))?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::PrCreated,
            None,
            Some(&format!("PR #{}", pr_info.number)),
            Some(&pr_info.url),
        )
        .map_err(|e| WorkspaceError::Event(e.to_string()))?;

    let mut attempts = 0u32;
    let ready = loop { // UNBOUNDED: event loop
        let status = connector
            .pr_readiness(repo_slug, pr_info.number)
            .await
            .map_err(|e| WorkspaceError::Merge(e.to_string()))?;
        if status.mergeable && status.ci_passed && status.unresolved_threads == 0 {
            break true;
        }
        attempts += 1;
        if attempts >= MAX_POLL_ATTEMPTS {
            break false;
        }
        sleep(Duration::from_secs(POLL_INTERVAL_SECS)).await;
    };

    if !ready {
        return Err(WorkspaceError::Merge(format!(
            "PR #{} not ready after {} attempts",
            pr_info.number, MAX_POLL_ATTEMPTS
        )));
    }

    connector
        .merge_pr(repo_slug, pr_info.number, MergeMethod::Squash)
        .await
        .map_err(|e| WorkspaceError::Merge(e.to_string()))?;
    event_logger
        .record_event(
            &workspace_id,
            "merge_ops",
            WorkspaceAction::PrMerged,
            None,
            Some(&format!("PR #{} squash-merged", pr_info.number)),
            None,
        )
        .map_err(|e| WorkspaceError::Event(e.to_string()))?;

    pool.get()?.execute(
        "UPDATE waves SET status='done', pr_number=?1, pr_url=?2 WHERE id=?3",
        params![pr_info.number, pr_info.url, wave_db_id],
    )?;

    Ok(MergeResult {
        pr_number: pr_info.number,
        pr_url: pr_info.url,
        merged: true,
    })
}

/// Thin wrapper around connector.pr_readiness for external callers.
pub async fn pr_readiness_check(
    connector: &dyn GitConnector,
    repo: &str,
    pr_number: i64,
) -> std::result::Result<PrReadiness, GitError> {
    connector.pr_readiness(repo, pr_number).await
}

#[cfg(test)]
#[path = "merge_ops_tests.rs"]
mod tests;
