#!/usr/bin/env bash
# setup-terminal-stack.sh — Cross-platform terminal stack installer
# Works on macOS (Homebrew) and Linux (apt + Homebrew for Rust tools)
# Idempotent: safe to re-run. Installs only what's missing.
#
# Usage:
#   bash setup-terminal-stack.sh              # full install
#   bash setup-terminal-stack.sh --tools-only # skip shell/tmux config
#   bash setup-terminal-stack.sh --config-only # skip tool install
set -euo pipefail

# ── Detect OS ─────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"
TOOLS_ONLY=false
CONFIG_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --tools-only)  TOOLS_ONLY=true ;;
    --config-only) CONFIG_ONLY=true ;;
  esac
done

ok()   { printf '  \033[0;32m[OK]\033[0m   %s\n' "$1"; }
skip() { printf '  \033[0;33m[SKIP]\033[0m %s\n' "$1"; }
info() { printf '  \033[0;36m[..]\033[0m   %s\n' "$1"; }
fail() { printf '  \033[0;31m[FAIL]\033[0m %s\n' "$1"; }

has() { command -v "$1" &>/dev/null; }

# ── Core tools to install ─────────────────────────────────
BREW_TOOLS=(tmux fzf eza bat zoxide starship fd ripgrep lazygit yazi atuin)
APT_TOOLS=(tmux fzf zsh git curl gcc make)

echo "=== Terminal Stack Setup ==="
echo "OS: $OS ($ARCH)"
echo ""

# ── Step 1: Package manager ──────────────────────────────
install_tools() {
  if [[ "$OS" == "Darwin" ]]; then
    if ! has brew; then
      info "Installing Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
    ok "Homebrew"

    # Install Ghostty if not present (macOS only)
    if [[ ! -d "/Applications/Ghostty.app" ]]; then
      info "Installing Ghostty..."
      brew install --cask ghostty
    fi
    ok "Ghostty"

    # Install Nerd Font
    if ! system_profiler SPFontsDataType 2>/dev/null | grep -q "JetBrainsMono Nerd Font"; then
      info "Installing JetBrainsMono Nerd Font..."
      brew install --cask font-jetbrains-mono-nerd-font
    fi
    ok "JetBrainsMono Nerd Font"

    # Install brew tools
    local missing=()
    for tool in "${BREW_TOOLS[@]}"; do
      if ! has "$tool"; then
        missing+=("$tool")
      fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
      info "Installing: ${missing[*]}"
      brew install "${missing[@]}"
    fi
    ok "CLI tools (${BREW_TOOLS[*]})"

  elif [[ "$OS" == "Linux" ]]; then
    # System packages
    info "Installing system packages..."
    sudo apt update -qq
    sudo apt install -y -qq "${APT_TOOLS[@]}" 2>/dev/null
    ok "System packages"

    # Homebrew for Linux (for Rust-based tools)
    if ! has brew; then
      info "Installing Homebrew for Linux..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    fi
    ok "Homebrew (Linux)"

    # Install remaining tools via brew
    local missing=()
    for tool in "${BREW_TOOLS[@]}"; do
      if ! has "$tool"; then
        missing+=("$tool")
      fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
      info "Installing: ${missing[*]}"
      brew install "${missing[@]}"
    fi
    ok "CLI tools"
  fi
}

# ── Step 2: TPM (Tmux Plugin Manager) ────────────────────
install_tpm() {
  local tpm_dir="$HOME/.tmux/plugins/tpm"
  if [[ ! -d "$tpm_dir" ]]; then
    info "Installing TPM..."
    git clone https://github.com/tmux-plugins/tpm "$tpm_dir"
  else
    info "Updating TPM..."
    (cd "$tpm_dir" && git pull -q)
  fi
  ok "TPM"
}

# ── Step 3: Tmux config ──────────────────────────────────
install_tmux_config() {
  local src="${CONVERGIO_PLATFORM_DIR:-$HOME/GitHub/ConvergioPlatform}/scripts/platform"
  local tmux_conf="$HOME/.tmux.conf"

  # If running from ConvergioPlatform, use the canonical config
  # Otherwise check if the user already has one
  if [[ -f "$tmux_conf" ]]; then
    ok ".tmux.conf exists"
  else
    # Generate a minimal config if no ConvergioPlatform source
    cat > "$tmux_conf" << 'TMUX_EOF'
# Generated by setup-terminal-stack.sh
# Full config: github.com/Roberdan/ConvergioPlatform
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-ghostty:Tc,xterm-256color:Tc"
set -g mouse on
set -s escape-time 0
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D
bind r source-file ~/.tmux.conf \; display "Config reloaded"
setw -g mode-keys vi
set -g status-style "bg=#0d2045,fg=#a5d5fe"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
run '~/.tmux/plugins/tpm/tpm'
TMUX_EOF
    ok ".tmux.conf created"
  fi

  # Install TPM plugins non-interactively
  if [[ -x "$HOME/.tmux/plugins/tpm/bin/install_plugins" ]]; then
    info "Installing tmux plugins..."
    "$HOME/.tmux/plugins/tpm/bin/install_plugins" >/dev/null 2>&1 || true
    ok "Tmux plugins installed"
  fi
}

# ── Step 4: Zsh plugin setup ─────────────────────────────
install_zsh_plugins() {
  mkdir -p "$HOME/.zsh"

  # zsh-autosuggestions
  local auto_dir="$HOME/.zsh/zsh-autosuggestions"
  if [[ ! -d "$auto_dir" ]]; then
    info "Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions "$auto_dir"
  else
    (cd "$auto_dir" && git pull -q 2>/dev/null)
  fi
  ok "zsh-autosuggestions"

  # zsh-syntax-highlighting
  local syn_dir="$HOME/.zsh/zsh-syntax-highlighting"
  if [[ ! -d "$syn_dir" ]]; then
    info "Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$syn_dir"
  else
    (cd "$syn_dir" && git pull -q 2>/dev/null)
  fi
  ok "zsh-syntax-highlighting"

  # Add to .zshrc if not already sourced
  local zshrc="$HOME/.zshrc"
  if [[ -f "$zshrc" ]]; then
    if ! grep -q 'zsh-autosuggestions' "$zshrc"; then
      info "Adding zsh plugins to .zshrc..."
      cat >> "$zshrc" << 'ZSH_EOF'

# === Zsh Plugins (added by setup-terminal-stack.sh) ===
[[ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -f ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_EOF
      ok "Zsh plugins added to .zshrc"
    else
      ok "Zsh plugins already in .zshrc"
    fi
  fi
}

# ── Step 5: Atuin init ────────────────────────────────────
setup_atuin() {
  if ! has atuin; then
    skip "Atuin not installed"
    return
  fi

  local zshrc="$HOME/.zshrc"
  if [[ -f "$zshrc" ]] && ! grep -q 'atuin init' "$zshrc"; then
    # Insert atuin before zoxide (which must be last)
    if grep -q 'zoxide init' "$zshrc"; then
      local tmp
      tmp=$(mktemp)
      sed '/eval "\$(zoxide init zsh)"/i\
eval "$(atuin init zsh)"' "$zshrc" > "$tmp" && mv "$tmp" "$zshrc"
      ok "Atuin init added to .zshrc (before zoxide)"
    else
      echo 'eval "$(atuin init zsh)"' >> "$zshrc"
      ok "Atuin init added to .zshrc"
    fi
  else
    ok "Atuin already in .zshrc"
  fi
}

# ── Step 6: Verify ────────────────────────────────────────
verify() {
  echo ""
  echo "=== Verification ==="
  local all_ok=true
  for tool in tmux fzf eza bat zoxide starship fd rg lazygit atuin; do
    if has "$tool"; then
      ok "$tool $(command $tool --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+[^ ]*' | head -1)"
    else
      fail "$tool not found"
      all_ok=false
    fi
  done

  if [[ -f "$HOME/.tmux.conf" ]]; then
    ok ".tmux.conf"
  else
    fail ".tmux.conf missing"
    all_ok=false
  fi

  if [[ -d "$HOME/.tmux/plugins/tpm" ]]; then
    ok "TPM installed"
  else
    fail "TPM missing"
    all_ok=false
  fi

  echo ""
  if $all_ok; then
    echo "=== Setup Complete ==="
  else
    echo "=== Setup Complete (with warnings) ==="
  fi

  echo ""
  echo "Next steps:"
  echo "  1. Restart your shell: source ~/.zshrc"
  echo "  2. Start tmux: tmux new -s convergio"
  echo "  3. Tmux plugins auto-install on first launch"
  echo "  4. Press Up-Arrow to try Atuin history search"
  echo "  5. Type 'z <dir>' for smart cd with Zoxide"
  echo ""
}

# ── Main ──────────────────────────────────────────────────
if ! $CONFIG_ONLY; then
  install_tools
fi

if ! $TOOLS_ONLY; then
  install_tpm
  install_tmux_config
  install_zsh_plugins
  setup_atuin
fi

verify
