#!/usr/bin/env bash
set -euo pipefail
# build-usb.sh — Package ConvergioMesh for USB delivery
# Usage: build-usb.sh /Volumes/USBNAME

USB_TARGET="${1:?Usage: build-usb.sh /Volumes/USBNAME}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_ROOT/build"

[ -d "$USB_TARGET" ] || { echo "ERROR: $USB_TARGET not found"; exit 1; }

# Build DMG if not exists
[ -f "$BUILD_DIR/ConvergioMesh.dmg" ] || "$SCRIPT_DIR/build-dmg.sh"

echo "=== Copying to USB ==="
DEST="$USB_TARGET/ConvergioMesh"
mkdir -p "$DEST"

# Copy DMG
cp "$BUILD_DIR/ConvergioMesh.dmg" "$DEST/"

# Copy standalone CLI (for terminal users)
cp "$PROJECT_ROOT/target/release/convergiomesh-cli" "$DEST/"

# Export curated Brewfile from this machine
if command -v brew &>/dev/null; then
    brew bundle dump --file="$DEST/Brewfile" --force 2>/dev/null || true
fi

# Copy profiles
cp -r "$PROJECT_ROOT/profiles" "$DEST/" 2>/dev/null || true

# Create README
cat > "$DEST/README.txt" << 'EOF'
ConvergioMesh — Mesh Node Onboarding

INSTALL:
1. Open ConvergioMesh.dmg
2. Drag ConvergioMesh to Applications
3. Launch ConvergioMesh
4. Enter your invite token

OR via terminal:
  ./convergiomesh-cli join <token>

Generated by build-usb.sh
EOF

echo "=== USB package ready at $DEST ==="
ls -la "$DEST"
